 # **Data Linkage without having explicit primary key**

# 1. Data collection

In [219]:
import pandas as pd

In [201]:
df6=pd.read_csv(r"/home/japan/AMIT KUMAR/DC/Data/RRUFF_Export_20230608_052338.csv", encoding='latin-1')

In [202]:
df6

,Mineral Name,RRUFF Chemistry (plain),IMA Chemistry (plain),Chemistry Elements,IMA Number,RRUFF IDs,Country of Type Locality,Year First Published,IMA Status,Structural Groupname,Fleischers Groupname,Status Notes,Crystal Systems,Space Groups,Oldest Known Age (Ma),Valence Elements,Paragenetic Modes
0,Abellaite,NaPb2+2(CO3)2(OH),NaPb2(CO3)2(OH),Na Pb C O H,IMA2014-111,NaN,Spain,2014,Approved,Not in a structural group,Â,"IbÃ¡Ã±ez-Insa J, Elvira J J, Llovet X, PÃ©rez-...",hexagonal,P31c|P6_3mc,370.0,Na Pb^2+ C O H,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."
1,Abelsonite,Ni2+C31H32N4,NiC31H32N4,Ni C H N,IMA1975-013,R070007,USA,1975,Approved,Not in a structural group,Â,"Milton C, Dwornik E J, Estep-Barnes P A, Finke...",triclinic,P-1,56.0,Ni^2+ C H N,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."
2,Abenakiite-(Ce),Na26Ce3+6(SiO3)6(PO4)6(C4+O3)6(S4+O2)O,Na26Ce6(Si6O18)(PO4)6(CO3)6(SO2)O,Na Ce Si O P C S,IMA1991-054,NaN,Canada,1991,Approved,Not in a structural group,Â,"McDonald A M, Chao G Y, Grice J D (1994) Abena...",hexagonal,R-3,124.0,Na Ce^3+ Si O P C^4+ S^4+,"Abiotic, Primary; Stage 4b: Highly evolved ign..."
3,Abernathyite,K(U6+O2)As5+O4Â·3H2O,K(UO2)(AsO4)Â·3H2O,K U O As H,NaN,NaN,USA,1956,"Approved,Grandfathered",Natroautunite,autunite,"Thompson M E, Ingram B, Gross E B (1956) Abern...",tetragonal,P4/nmm|P4/ncc,358.9,K U^6+ O As^5+ H,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."
4,Abhurite,Sn2+21O6(OH)14Cl16,Sn2+21O6(OH)14Cl16,Sn O H Cl,IMA1983-061,R060227,Saudi Arabia,1983,Approved,Not in a structural group,Â,"Matzko J J, Evans H T, Mrose M E, Aruscavage P...",hexagonal,R32,0.0,Sn^2+ O H Cl,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5899,ZvÄstovite-(Zn),Ag1+6(Ag1+4Zn2+2)As3+4S2-13,Ag6(Ag4Zn2)As4S13,Ag Zn As S,IMA2020-061,NaN,Czech Republic,2020,Approved,Tetrahedrite,Â,"Sejkora J, Biagioni C, VrtiÅ¡ka L, MoÃ«lo Y (2...",cubic,I-43m,NaN,Ag^1+ Zn^2+ As^3+ S^2-,"Abiotic, Primary; Stage 4a: Earth's earliest c..."
5900,Zvyaginite,Na2Zn2+Ti4+Nb5+2(Si2O7)2O2(OH)2(H2O)4,Na2ZnTiNb2(Si2O7)2O2(OH)2(H2O)4,Na Zn Ti Nb Si O H,IMA2013-071,NaN,Russia,2013,"Approved,Redefined",Seidozerite-Lamprophyllite,Â,"Pekov I V, Lykova I S, Chukanov N V, Yapaskurt...",triclinic,P-1,370.0,Na Zn^2+ Ti^4+ Nb^5+ Si O H,"Abiotic, Primary; Stage 4b: Highly evolved ign..."
5901,Zvyagintsevite,Pd3Pb,Pd3Pb,Pd Pb,IMA1966-006,NaN,Russia,1966,Approved,"Perovskite, Auricupride",zvyagintsevite,"Genkin A D, MuravÂ´eva I V, Troneva N V (1966)...",cubic,Pm3m,3100.0,Pd Pb,"Abiotic, Primary, Secondary; Stage 2: Planetes..."
5902,Zwieselite,Fe2+2PO4F,Fe2+2(PO4)F,Fe P O F,NaN,R050279,Germany,1841,"Approved,Redefined",Triplite,triplite,Breithaupt J F A (1841) Phyletites ferrosus od...,monoclinic,I2/a,1820.0,Fe^2+ P O F,"Abiotic, Primary; Stage 4b: Highly evolved ign..."
5903,ZÃ½kaite,Fe3+4(As5+O4)3S6+O4(OH)Â·15H2O,Fe3+4(AsO4)3(SO4)(OH)Â·15H2O,Fe As O S H,IMA1976-039,R070477,Czech Republic,1976,Approved,Â,Â,"Äech F, Jansa J, NovÃ¡k F (1978) ZÃ½kaite, Fe...",orthorhombic|unknown,NaN,0.0,Fe^3+ As^5+ O S^6+ H,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."

In [203]:
df_1 = df6.loc[:, ['Mineral Name', 'Chemistry Elements','Year First Published']]
df_2 = df6.loc[:, ['RRUFF Chemistry (plain)', 'RRUFF IDs','Country of Type Locality']]
df_3 = df6.loc[:, ['IMA Chemistry (plain)', 'IMA Number']]
df_4 = df6.loc[:, ['Structural Groupname', 'Crystal Systems','IMA Status']]
df_5 = df6.loc[:, ['Status Notes', 'Fleischers Groupname','Space Groups']]
df_6 = df6.loc[:, ['Oldest Known Age (Ma)', 'Valence Elements','Paragenetic Modes']]
#df_1

In [204]:
df_1

          Mineral Name  Chemistry Elements  Year First Published
0            Abellaite         Na Pb C O H                  2014
1           Abelsonite            Ni C H N                  1975
2      Abenakiite-(Ce)    Na Ce Si O P C S                  1991
3         Abernathyite          K U O As H                  1956
4             Abhurite           Sn O H Cl                  1983
...                ...                 ...                   ...
5899  ZvÄstovite-(Zn)          Ag Zn As S                  2020
5900        Zvyaginite  Na Zn Ti Nb Si O H                  2013
5901    Zvyagintsevite               Pd Pb                  1966
5902        Zwieselite            Fe P O F                  1841
5903          ZÃ½kaite         Fe As O S H                  1976

[5904 rows x 3 columns]

In [205]:
df_2

,RRUFF Chemistry (plain),RRUFF IDs,Country of Type Locality
0,NaPb2+2(CO3)2(OH),NaN,Spain
1,Ni2+C31H32N4,R070007,USA
2,Na26Ce3+6(SiO3)6(PO4)6(C4+O3)6(S4+O2)O,NaN,Canada
3,K(U6+O2)As5+O4Â·3H2O,NaN,USA
4,Sn2+21O6(OH)14Cl16,R060227,Saudi Arabia
...,...,...,...
5899,Ag1+6(Ag1+4Zn2+2)As3+4S2-13,NaN,Czech Republic
5900,Na2Zn2+Ti4+Nb5+2(Si2O7)2O2(OH)2(H2O)4,NaN,Russia
5901,Pd3Pb,NaN,Russia
5902,Fe2+2PO4F,R050279,Germany
5903,Fe3+4(As5+O4)3S6+O4(OH)Â·15H2O,R070477,Czech Republic

In [206]:
df_3

                  IMA Chemistry (plain)   IMA Number
0                       NaPb2(CO3)2(OH)  IMA2014-111
1                            NiC31H32N4  IMA1975-013
2     Na26Ce6(Si6O18)(PO4)6(CO3)6(SO2)O  IMA1991-054
3                    K(UO2)(AsO4)Â·3H2O          NaN
4                    Sn2+21O6(OH)14Cl16  IMA1983-061
...                                 ...          ...
5899                  Ag6(Ag4Zn2)As4S13  IMA2020-061
5900    Na2ZnTiNb2(Si2O7)2O2(OH)2(H2O)4  IMA2013-071
5901                              Pd3Pb  IMA1966-006
5902                        Fe2+2(PO4)F          NaN
5903       Fe3+4(AsO4)3(SO4)(OH)Â·15H2O  IMA1976-039

[5904 rows x 2 columns]

In [207]:
df_4

            Structural Groupname       Crystal Systems              IMA Status
0      Not in a structural group             hexagonal                Approved
1      Not in a structural group             triclinic                Approved
2      Not in a structural group             hexagonal                Approved
3                  Natroautunite            tetragonal  Approved,Grandfathered
4      Not in a structural group             hexagonal                Approved
...                          ...                   ...                     ...
5899                Tetrahedrite                 cubic                Approved
5900  Seidozerite-Lamprophyllite             triclinic      Approved,Redefined
5901     Perovskite, Auricupride                 cubic                Approved
5902                    Triplite            monoclinic      Approved,Redefined
5903                          Â   orthorhombic|unknown                Approved

[5904 rows x 3 columns]

In [208]:
df_5

,Status Notes,Fleischers Groupname,Space Groups
0,"IbÃ¡Ã±ez-Insa J, Elvira J J, Llovet X, PÃ©rez-...",Â,P31c|P6_3mc
1,"Milton C, Dwornik E J, Estep-Barnes P A, Finke...",Â,P-1
2,"McDonald A M, Chao G Y, Grice J D (1994) Abena...",Â,R-3
3,"Thompson M E, Ingram B, Gross E B (1956) Abern...",autunite,P4/nmm|P4/ncc
4,"Matzko J J, Evans H T, Mrose M E, Aruscavage P...",Â,R32
...,...,...,...
5899,"Sejkora J, Biagioni C, VrtiÅ¡ka L, MoÃ«lo Y (2...",Â,I-43m
5900,"Pekov I V, Lykova I S, Chukanov N V, Yapaskurt...",Â,P-1
5901,"Genkin A D, MuravÂ´eva I V, Troneva N V (1966)...",zvyagintsevite,Pm3m
5902,Breithaupt J F A (1841) Phyletites ferrosus od...,triplite,I2/a
5903,"Äech F, Jansa J, NovÃ¡k F (1978) ZÃ½kaite, Fe...",Â,NaN

In [209]:
df_6

,Oldest Known Age (Ma),Valence Elements,Paragenetic Modes
0,370.0,Na Pb^2+ C O H,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."
1,56.0,Ni^2+ C H N,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."
2,124.0,Na Ce^3+ Si O P C^4+ S^4+,"Abiotic, Primary; Stage 4b: Highly evolved ign..."
3,358.9,K U^6+ O As^5+ H,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."
4,0.0,Sn^2+ O H Cl,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."
...,...,...,...
5899,NaN,Ag^1+ Zn^2+ As^3+ S^2-,"Abiotic, Primary; Stage 4a: Earth's earliest c..."
5900,370.0,Na Zn^2+ Ti^4+ Nb^5+ Si O H,"Abiotic, Primary; Stage 4b: Highly evolved ign..."
5901,3100.0,Pd Pb,"Abiotic, Primary, Secondary; Stage 2: Planetes..."
5902,1820.0,Fe^2+ P O F,"Abiotic, Primary; Stage 4b: Highly evolved ign..."
5903,0.0,Fe^3+ As^5+ O S^6+ H,"Biotic, Secondary; Stage 7: Great Oxidation Ev..."